# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/modelsim/win32pe
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/demo/FGPA/0/0/project_14/project_14.cache/wt [current_project]
set_property parent.project_path E:/demo/FGPA/0/0/project_14/project_14.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/demo/FGPA/0/0/project_14/project_14.srcs/sources_1/new/seg_num_060.v
  E:/demo/FGPA/0/0/project_14/project_14.srcs/sources_1/new/sel_det_060.v
  E:/demo/FGPA/0/0/project_14/project_14.srcs/sources_1/new/divclk_060.v
  E:/demo/FGPA/0/0/project_14/project_14.srcs/sources_1/new/det.v
  E:/demo/FGPA/0/0/project_14/project_14.srcs/sources_1/new/process_060.v
  E:/demo/FGPA/0/0/project_14/project_14.srcs/sources_1/new/CarC.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/demo/FGPA/0/0/project_14/project_14.srcs/constrs_1/new/CarC.xdc
set_property used_in_implementation false [get_files E:/demo/FGPA/0/0/project_14/project_14.srcs/constrs_1/new/CarC.xdc]


synth_design -top carMove -part xc7a100tcsg324-1


write_checkpoint -force -noxdef carMove.dcp

catch { report_utilization -file carMove_utilization_synth.rpt -pb carMove_utilization_synth.pb }
